using Microsoft.CodeAnalysis;

namespace GeneratorSample;

[Generator(LanguageNames.CSharp)]
public class HelloWorldGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.AdditionalTextsProvider, (ctx, _) =>
        {
            // コード生成
            ctx.AddSource("HelloWorld.g.cs", """
            // <auto-generated />
            namespace GeneratorSample;

            public class HelloWorld 
            {
                public string Message => "Hello, World!";
            }
            """);
        });
    }
}